# Generated by Django 4.2.9 on 2024-08-06 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 8, 6, 10, 18, 43, 343456, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
